# Generated by Django 5.1.4 on 2025-02-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
