# Generated by Django 5.1.4 on 2025-02-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_favorite_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='quantity',
        ),
    ]
